/* ============================================================
   PROYECTO: WINE_WORLD_WIDE
   FICHERO: DO_Cava.sql
   DESCRIPCIÓN: Consultas SQL para la DO Cava por Subzonas y Total.
   ============================================================ */

-- SUBZONA: VALLS D’ANOIA – FOIX
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Abrera',
'Aiguamúrcia',
'Albinyana',
'Avinyonet del Penedès',
'Banyeres del Penedès',
'Begues',
'Bellvei',
'Bonastre',
'Cabrera d''Anoia',
'Calafell',
'Canyelles',
'Castellet i la Gornal',
'Castellví de la Marca',
'Castellví de Rosanes',
'Cervelló',
'Corbera de Llobregat',
'Cubelles',
'Cunit',
'El Montmell',
'El Pla del Penedès',
'El Vendrell',
'Els Hostelets de Pierola',
'Font-rubí',
'Gelida',
'La Bisbal del Penedès',
'La Granada',
'La Llacuna',
'La Pobla de Claramunt',
'L''Arboç',
'Les Cabanyes',
'Llorenç del Penedès',
'Martorell',
'Masquefa',
'Mediona',
'Òdena',
'Olèrdola',
'Olesa de Bonesvalls',
'Olivella',
'Pacs del Penedès',
'Piera',
'Pontons',
'Puigdalber',
'Rubí',
'Sant Cugat Sesgarrigues',
'Sant Esteve Sesrovires',
'Sant Jaume dels Domenys',
'Sant Llorenç d''Hortons',
'Sant Martí Sarroca',
'Sant Pere de Ribes',
'Sant Pere de Riudebitlles',
'Sant Quintí de Mediona',
'Sant Sadurní d''Anoia',
'Santa Fe del Penedès',
'Santa Margarida i els Monjos',
'Santa Maria de Miralles',
'Santa Oliva',
'Sitges',
'Subirats',
'Torrelavit',
'Torrelles de Foix',
'Vallbona d''Anoia',
'Vallirana',
'Vilafranca del Penedès',
'Vilanova i la Geltrú',
'Vilobí del Penedès'
)

-- SUBZONA: SERRA DE MAR
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Alella',
'Cabrils',
'El Masnou',
'Martorelles',
'Montgat',
'Premià de Mar',
'Sant Fost de Campsentelles',
'Santa Maria de Martorelles',
'Teià',
'Tiana',
'Vilassar de Dalt'
)

-- SUBZONA: CONCA DEL GAIÀ
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Alió',
'Bràfim',
'Cabra del Camp',
'Creixell',
'El Catllar',
'El Pla de Santa Maria',
'Els Garidells',
'Els Pallaresos',
'Figuerola del Camp',
'La Nou de Gaià',
'La Riera de Gaià',
'La Secuita',
'Masllorenç',
'Montferri',
'Nulles',
'Perafort',
'Puigpelat',
'Renau',
'Roda de Berà',
'Rodonyà',
'Salomó',
'Vallmoll',
'Valls',
'Vespella de Gaià',
'Vilabella',
'Vila-rodona',
'Vila-seca'
)

-- SUBZONA: SERRA DE PRADES
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Barberà de la Conca',
'Blancafort',
'L''Espluga de Francolí',
'Montblanc',
'Pira',
'Rocafort de Queralt',
'Sarral',
'Solivella',
'Vilaverd',
'Vimbodí i Poblet'
)

-- SUBZONA: PLA DE PONENT
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'El Vilosell',
'Fulleda',
'Guimerà',
'L''Albi',
'L''Espluga Calva',
'Lleida',
'Maldà',
'Sant Martí de Riucorb',
'Tarrés',
'Verdú',
'Vinaixa'
)

-- SUBZONA: ALTO EBRO
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Alesanco',
'Azofra',
'Briones',
'Casalarreina',
'Cihuri',
'Cordovín',
'Cuzcurrita de Río Tirón',
'Fonzaleche',
'Grávalos',
'Haro',
'Hormilla',
'Hormilleja',
'Laguardia',
'Mendavia',
'Moreda de Álava/Moreda Araba',
'Nájera',
'Oyón-Oion',
'Sajazarra',
'San Asensio',
'Tirgo',
'Uruñuela',
'Viana',
'Villalba de Rioja'
)

-- SUBZONA: VALLE DEL CIERZO
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Ainzón',
'Cariñena'
)

-- ZONA: VIÑEDOS DE ALMENDRALEJO
-- ------------------------------------------------------------
"NAMEUNIT" = 'Almendralejo'

-- ZONA: REQUENA
-- ------------------------------------------------------------
"NAMEUNIT" = 'Requena'

-- EXCEPCIONES HISTÓRICAS
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Aranda de Duero',
'Calatayud',
'Cornellà de Llobregat',
'Garriguella',
'Turís'
)

-- CONSULTA GLOBAL: TODOS LOS MUNICIPIOS DO CAVA
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Abrera',
'Aiguamúrcia',
'Ainzón',
'Albinyana',
'Alella',
'Alió',
'Almendralejo',
'Aranda de Duero',
'Avinyonet del Penedès',
'Alesanco',
'Azofra',
'Banyeres del Penedès',
'Barberà de la Conca',
'Begues',
'Bellvei',
'Blancafort',
'Bràfim',
'Briones',
'Cabrera d''Anoia',
'Cabrils',
'Cabra del Camp',
'Calafell',
'Calatayud',
'Canyelles',
'Cariñena',
'Casalarreina',
'Castellet i la Gornal',
'Castellví de la Marca',
'Castellví de Rosanes',
'Cervelló',
'Cihuri',
'Corbera de Llobregat',
'Cordovín',
'Cornellà de Llobregat',
'Creixell',
'Cubelles',
'Cunit',
'Cuzcurrita de Río Tirón',
'El Catllar',
'El Masnou',
'El Montmell',
'El Pla del Penedès',
'El Pla de Santa Maria',
'El Vendrell',
'El Vilosell',
'Els Garidells',
'Els Hostelets de Pierola',
'Els Pallaresos',
'Figuerola del Camp',
'Font-rubí',
'Fonzaleche',
'Fulleda',
'Garriguella',
'Gelida',
'Grávalos',
'Guimerà',
'Haro',
'Hormilla',
'Hormilleja',
'L''Albi',
'L''Arboç',
'L''Espluga Calva',
'L''Espluga de Francolí',
'La Bisbal del Penedès',
'La Granada',
'La Llacuna',
'La Nou de Gaià',
'La Pobla de Claramunt',
'La Riera de Gaià',
'La Secuita',
'Laguardia',
'Les Cabanyes',
'Lleida',
'Llorenç del Penedès',
'Maldà',
'Martorell',
'Martorelles',
'Masllorenç',
'Masquefa',
'Mediona',
'Mendavia',
'Montblanc',
'Montferri',
'Montgat',
'Moreda de Álava/Moreda Araba',
'Nájera',
'Nulles',
'Òdena',
'Olèrdola',
'Olesa de Bonesvalls',
'Olivella',
'Oyón-Oion',
'Pacs del Penedès',
'Perafort',
'Piera',
'Pira',
'Pontons',
'Premià de Mar',
'Puigdalber',
'Puigpelat',
'Renau',
'Requena',
'Rocafort de Queralt',
'Roda de Berà',
'Rodonyà',
'Rubí',
'Sajazarra',
'Salomó',
'San Asensio',
'Sant Cugat Sesgarrigues',
'Sant Esteve Sesrovires',
'Sant Fost de Campsentelles',
'Sant Jaume dels Domenys',
'Sant Llorenç d''Hortons',
'Sant Martí de Riucorb',
'Sant Martí Sarroca',
'Sant Pere de Ribes',
'Sant Pere de Riudebitlles',
'Sant Quintí de Mediona',
'Sant Sadurní d''Anoia',
'Santa Fe del Penedès',
'Santa Margarida i els Monjos',
'Santa Maria de Martorelles',
'Santa Maria de Miralles',
'Santa Oliva',
'Sarral',
'Sitges',
'Solivella',
'Subirats',
'Tarrés',
'Teià',
'Tiana',
'Tirgo',
'Torrelavit',
'Torrelles de Foix',
'Turís',
'Uruñuela',
'Vallbona d''Anoia',
'Vallmoll',
'Vallirana',
'Valls',
'Verdú',
'Vespella de Gaià',
'Viana',
'Vilabella',
'Vilafranca del Penedès',
'Vilanova i la Geltrú',
'Vila-rodona',
'Vila-seca',
'Vilaverd',
'Villalba de Rioja',
'Vilassar de Dalt',
'Vilobí del Penedès',
'Vimbodí i Poblet',
'Vinaixa'
)
