/* ============================================================
   PROYECTO: WINE_WORLD_WIDE
   FICHERO: DOCas.sql
   VERSION: Verificada con recintos_municipales_NAMEUNIT.csv
   ============================================================ */

-- DOCa RIOJA - SUBZONA: RIOJA ALTA
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Ábalos',
'Alesanco',
'Alesón',
'Anguciana',
'Arenzana de Abajo',
'Arenzana de Arriba',
'Azofra',
'Badarán',
'Bañares',
'Baños de Rioja',
'Baños de Río Tobía',
'Berceo',
'Bezares',
'Bobadilla',
'Briñas',
'Briones',
'Camprovín',
'Canillas de Río Tuerto',
'Casalarreina',
'Castañares de Rioja',
'Cañas',
'Cárdenas',
'Cellórigo',
'Cenicero',
'Cidamón',
'Cihuri',
'Cirueña',
'Cordovín',
'Cuzcurrita de Río Tirón',
'Daroca de Rioja',
'Entrena',
'Estollo',
'Foncea',
'Fonzaleche',
'Fuenmayor',
'Galbárruli',
'Gimileo',
'Haro',
'Herramélluri',
'Hervías',
'Hormilla',
'Hormilleja',
'Hornos de Moncalvillo',
'Huércanos',
'Lardero',
'Leiva',
'Logroño',
'Manjarrés',
'Matute',
'Medrano',
'Miranda de Ebro',
'Nájera',
'Navarrete',
'Ochánduri',
'Ollauri',
'Rodezno',
'Sajazarra',
'San Asensio',
'San Millán de Yécora',
'San Torcuato',
'San Vicente de la Sonsierra',
'Santa Coloma',
'Sojuela',
'Sorzano',
'Sotés',
'Tirgo',
'Tormantos',
'Torrecilla sobre Alesanco',
'Torremontalbo',
'Treviana',
'Tricio',
'Uruñuela',
'Ventosa',
'Villalba de Rioja',
'Villar de Torre',
'Villarejo',
'Zarratón'
)

-- DOCa RIOJA - SUBZONA: RIOJA ORIENTAL
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Agoncillo',
'Aguilar del Río Alhama',
'Albelda de Iregua',
'Alberite',
'Alcanadre',
'Aldeanueva de Ebro',
'Alfaro',
'Andosilla',
'Aras',
'Arnedillo',
'Arnedo',
'Arrúbal',
'Ausejo',
'Autol',
'Azagra',
'Bargota',
'Bergasa',
'Bergasillas Bajera',
'Calahorra',
'Cervera del Río Alhama',
'Clavijo',
'Corera',
'Cornago',
'El Redal',
'El Villar de Arnedo',
'Galilea',
'Grávalos',
'Herce',
'Igea',
'Lagunilla de Jubera',
'Leza de Río Leza',
'Mendavia',
'Molinos de Ocón',
'Murillo de Río Leza',
'Muro de Aguas',
'Nalda',
'Ocón',
'Pradejón',
'Préjano',
'Quel',
'Ribafrecha',
'Rincón de Soto',
'San Adrián',
'Santa Engracia de Jubera',
'Santa Eulalia Bajera',
'Sartaguda',
'Tudelilla',
'Viana',
'Villamediana de Iregua',
'Villarroya'
)

-- DOCa RIOJA - SUBZONA: RIOJA ALAVESA
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Baños de Ebro/Mañueta',
'Elciego',
'Elvillar/Bilar',
'Kripan',
'Labastida/Bastida',
'Laguardia',
'Lanciego/Lantziego',
'Lapuebla de Labarca',
'Leza',
'Moreda de Álava/Moreda Araba',
'Navaridas',
'Oyón-Oion',
'Samaniego',
'Villabuena de Álava/Eskuernaga',
'Yécora/Iekora'
)

-- DOCa PRIORAT
-- ------------------------------------------------------------
"NAMEUNIT" IN (
'Bellmunt del Priorat',
'Falset',
'Gratallops',
'El Lloar',
'La Morera de Montsant',
'Poboleda',
'Porrera',
'Torroja del Priorat',
'La Vilella Alta',
'La Vilella Baixa'
)
